3A/sibd/pgmshop/src/main/java/fr/pgmshop/entity/order/OrderLine.java
package fr.pgmshop.entity.order;

import fr.pgmshop.entity.catalog.Item;
import fr.pgmshop.exception.ValidationException;
import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.*;

@Entity
@Table(name = "order_line")
public class OrderLine implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(nullable = false)
    private Integer quantity;
    @OneToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "item_id", nullable = false)
    private Item item;

    public OrderLine() {
    }

    public OrderLine(Integer quantity, Item item) {
        this.quantity = quantity;
        this.item = item;
    }

    @PrePersist
    @PreUpdate
    private void validateData() {
        if (quantity == null || quantity < 0) {
            throw new ValidationException("Invalid quantity");
        }
    }

    public BigDecimal getSubTotal() {
        BigDecimal result = new BigDecimal(quantity.intValue());
        result = result.multiply(item.getUnitCost());
        return result;
    }

    public Long getId() {
        return id;
    }

    public Integer getQuantity() {
        return quantity;
    }

    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    public Item getItem() {
        return item;
    }

    public void setItem(Item item) {
        this.item = item;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }

        OrderLine orderLine = (OrderLine) o;

        if (!id.equals(orderLine.id)) {
            return false;
        }
        if (!item.equals(orderLine.item)) {
            return false;
        }
        if (!quantity.equals(orderLine.quantity)) {
            return false;
        }

        return true;
    }

    @Override
    public int hashCode() {
        int result;
        result = quantity.hashCode();
        result = 31 * result + item.hashCode();
        return result;
    }

    /* 
     * Implémenation de la serialisation
     */
    
    @Override
    public String toString() {
        final StringBuilder sb = new StringBuilder();
        sb.append("OrderLine");
        sb.append("{id=").append(id);
        sb.append(", quantity=").append(quantity);
        sb.append(", item=").append(item);
        sb.append('}');
        return sb.toString();
    }
}

3A/sibd/pgmshop/src/main/java/fr/pgmshop/jsf/ShoppingCartController.java
package fr.pgmshop.jsf;

import fr.pgmshop.entity.Address;
import fr.pgmshop.entity.catalog.Item;
import fr.pgmshop.entity.customer.Customer;
import fr.pgmshop.entity.order.CreditCard;
import fr.pgmshop.entity.order.Order;
import fr.pgmshop.stateful.CartItem;
import fr.pgmshop.stateful.ShoppingCartLocal;
import fr.pgmshop.stateless.catalog.CatalogLocal;
import fr.pgmshop.stateless.order.OrderLocal;
import java.math.BigDecimal;
import java.util.List;
import javax.ejb.EJB;

public class ShoppingCartController extends Controller {

    @EJB
    private ShoppingCartLocal shoppingCartBean;
    @EJB
    private CatalogLocal catalogBean;
    @EJB
    private OrderLocal orderBean;
    private final String cname = this.getClass().getName();
    private CreditCard creditCard = new CreditCard();
    private Customer customer;
    private Address deliveryAddress;
    private Order order;

    public String addItemToCart() {
        final String mname = "addItemToCart";
        logger.entering(cname, mname);

        String navigateTo = null;

        try {
            Item item = catalogBean.findItem(getParamId("itemId"));
            shoppingCartBean.addItem(item);
            navigateTo = "item.added";
        } catch (Exception e) {
            addMessage(cname, mname, e);
        }

        logger.exiting(cname, mname, navigateTo);
        return navigateTo;
    }

    public String removeItemFromCart() {
        final String mname = "removeItemFromCart";
        logger.entering(cname, mname);

        String navigateTo = null;

        try {
            Item item = catalogBean.findItem(getParamId("itemId"));
            shoppingCartBean.removeItem(item);
        } catch (Exception e) {
            addMessage(cname, mname, e);
        }

        logger.exiting(cname, mname, navigateTo);
        return navigateTo;
    }

    public String updateQuantity() {
        final String mname = "updateQuantity";
        logger.entering(cname, mname);

        String navigateTo = null;

        logger.exiting(cname, mname, navigateTo);
        return navigateTo;
    }

    public String checkout() {
        final String mname = "checkout";
        logger.entering(cname, mname);

        String navigateTo = "cart.checked.out";

        logger.exiting(cname, mname, navigateTo);
        return navigateTo;
    }

    public String confirmOrder() {
        final String mname = "confirmOrder";
        logger.entering(cname, mname);

        String navigateTo = null;

        try {
		/* On vérifie d'abord si tous les articles de la commande 
		 * ne sont pas en rupture de stock
		 */
	    for (CartItem ci : shoppingCartBean.getCartItems())
	    {
		    if (ci.getItem().getQty() < ci.getQuantity())
		    {
			    throw new Exception("L'article " 
				    + ci.getItem().getName() 
				    + " n'est pas suffisamment approvisionné."
				    + " "
				    + "Vous en avez pris "
				    + ci.getQuantity()
				    + " alors que nous en avons "
				    + ci.getItem().getQty()
				    + " en stock. "
				    + "Supprimez quelques exemplaires de votre "
				    + "panier.");
		    }
	    }
            order = orderBean.createOrder(customer, deliveryAddress, creditCard, shoppingCartBean.getCartItems());
            shoppingCartBean.empty();
            navigateTo = "order.confirmed";
        } catch (Exception e) {
            addMessage(cname, mname, e);
        }

        logger.exiting(cname, mname, navigateTo);
        return navigateTo;
    }

    public BigDecimal getTotal() {
        return shoppingCartBean.getTotal();
    }

    public List<CartItem> getCartItems() {
        return shoppingCartBean.getCartItems();
    }

    public Customer getCustomer() {
        return customer;
    }

    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    public Address getDeliveryAddress() {
        return deliveryAddress;
    }

    public void setDeliveryAddress(Address deliveryAddress) {
        this.deliveryAddress = deliveryAddress;
    }

    public CreditCard getCreditCard() {
        return creditCard;
    }

    public void setCreditCard(CreditCard creditCard) {
        this.creditCard = creditCard;
    }

    public Order getOrder() {
        return order;
    }

    public void setOrder(Order order) {
        this.order = order;
    }
}

3A/sibd/pgmshop/src/main/java/fr/pgmshop/stateless/catalog/CatalogBean.java
package fr.pgmshop.stateless.catalog;

import fr.pgmshop.entity.catalog.Category;
import fr.pgmshop.entity.catalog.Item;
import fr.pgmshop.entity.catalog.Product;
import fr.pgmshop.exception.ValidationException;
import fr.pgmshop.util.Constants;
import java.io.Serializable;
import java.util.List;
import java.util.logging.Logger;
import javax.ejb.Stateless;
import javax.ejb.TransactionAttribute;
import javax.ejb.TransactionAttributeType;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

@SuppressWarnings(value = "unchecked")
@TransactionAttribute(value = TransactionAttributeType.REQUIRED)
@Stateless(name = "CatalogSB")
public class CatalogBean implements CatalogRemote, CatalogLocal, Serializable {

    @PersistenceContext(unitName = "pgmshopPU")
    private EntityManager em;
    private final String cname = this.getClass().getName();
    private static final Logger logger = Logger.getLogger(Constants.LOGGER_STATELESS);

    @Override
    public Category createCategory(final Category category) {
        final String mname = "getNewCategory";
        logger.entering(cname, mname, category);

        // On s'assure de la validité des paramètres
        if (category == null) {
            throw new ValidationException("Category object is null");
        }

        // L'objet est persisté en base de données
        em.persist(category);

        logger.exiting(cname, mname, category);
        return category;
    }

    @Override
    public Category findCategory(final Long categoryId) {
        final String mname = "findCategory";
        logger.entering(cname, mname, categoryId);

        // On s'assure de la validité des paramètres
        if (categoryId == null) {
            throw new ValidationException("Invalid id");
        }

        Category category;

        // On recherche l'objet à partir de son identifiant
        category = em.find(Category.class, categoryId);

        logger.exiting(cname, mname, category);
        return category;
    }

    @Override
    public void deleteCategory(final Category category) {
        final String mname = "deleteCategory";
        logger.entering(cname, mname, category);

        // On s'assure de la validité des paramètres
        if (category == null) {
            throw new ValidationException("Category object is null");
        }

        // On supprime l'objet de la base de données
        em.remove(em.merge(category));

        logger.exiting(cname, mname);
    }

    @Override
    public Category updateCategory(final Category category) {
        final String mname = "updateCategory";
        logger.entering(cname, mname, category);

        // On s'assure de la validité des paramètres
        if (category == null) {
            throw new ValidationException("Category object is null");
        }

        // On modifie l'objet de la base de données
        em.merge(category);

        logger.exiting(cname, mname, category);
        return category;
    }

    @Override
    public List<Category> findCategories() {
        final String mname = "findCategories";
        logger.entering(cname, mname);

        Query query;
        List<Category> categories;

        // On modifie l'objet de la base de données
        query = em.createQuery("SELECT c FROM Category c ORDER BY c.name");
        categories = query.getResultList();

        logger.exiting(cname, mname, categories.size());
        return categories;
    }

    @Override
    public Product createProduct(final Product product, final Category category) {
        final String mname = "createProduct";
        logger.entering(cname, mname, product);

        // On s'assure de la validité des paramètres
        if (product == null) {
            throw new ValidationException("Product object is null");
        }
        if (category == null) {
            throw new ValidationException("Product must be attached to a category");
        }

        product.setCategory(category);

        // L'objet est persisté en base de données
        em.persist(product);

        logger.exiting(cname, mname, product);
        return product;
    }

    @Override
    public Product findProduct(final Long productId) {
        final String mname = "findProduct";
        logger.entering(cname, mname, productId);

        // On s'assure de la validité des paramètres
        if (productId == null) {
            throw new ValidationException("Invalid id");
        }

        Product product;

        // On recherche l'objet à partir de son identifiant
        product = em.find(Product.class, productId);

        logger.exiting(cname, mname, product);
        return product;
    }

    @Override
    public void deleteProduct(final Product product) {
        final String mname = "deleteProduct";
        logger.entering(cname, mname, product);

        // On s'assure de la validité des paramètres
        if (product == null) {
            throw new ValidationException("Product object is null");
        }

        // On supprime l'objet de la base de données
        em.remove(em.merge(product));

        logger.exiting(cname, mname);
    }

    @Override
    public Product updateProduct(final Product product, final Category category) {
        final String mname = "updateProduct";
        logger.entering(cname, mname, product);

        // On s'assure de la validité des paramètres
        if (product == null) {
            throw new ValidationException("Product object is null");
        }
        if (category == null) {
            throw new ValidationException("Product must be attached to a category");
        }

        product.setCategory(category);

        // On modifie l'objet de la base de données
        em.merge(product);

        logger.exiting(cname, mname, product);
        return product;
    }

    @Override
    public List<Product> findProducts() {
        final String mname = "findCategories";
        logger.entering(cname, mname);

        Query query;
        List<Product> products;

        // On modifie l'objet de la base de données
        query = em.createQuery("SELECT p FROM Product p ORDER BY p.name");
        products = query.getResultList();

        logger.exiting(cname, mname, products.size());
        return products;
    }

    @Override
    public Item createItem(final Item item, final Product product) {
        final String mname = "createItem";
        logger.entering(cname, mname, item);

        // On s'assure de la validité des paramètres
        if (item == null) {
            throw new ValidationException("Item object is null");
        }
        if (product == null) {
            throw new ValidationException("Item must be attached to a product");
        }

        item.setProduct(product);

        // L'objet est persisté en base de données
        em.persist(item);

        logger.exiting(cname, mname, item);
        return item;
    }

    @Override
    public Item findItem(final Long itemId) {
        final String mname = "findItem";
        logger.entering(cname, mname, itemId);

        // On s'assure de la validité des paramètres
        if (itemId == null) {
            throw new ValidationException("Invalid id");
        }

        Item item;

        // On recherche l'objet à partir de son identifiant
        item = em.find(Item.class, itemId);


        logger.exiting(cname, mname, item);
        return item;
    }

    public int getItemCount() {
        Query q = em.createQuery("select count(o) from Item as o");
        int count = ((Long) q.getSingleResult()).intValue();
        return count;
    }

    @Override
    public void deleteItem(final Item item) {
        final String mname = "deleteItem";
        logger.entering(cname, mname, item);

        // On s'assure de la validité des paramètres
        if (item == null) {
            throw new ValidationException("Item object is null");
        }

        // On supprime l'objet de la base de données
        em.remove(em.merge(item));

        logger.exiting(cname, mname);
    }

    @Override
    public Item updateItem(final Item item, final Product product) {
        final String mname = "updateItem";
        logger.entering(cname, mname, item);

        // On s'assure de la validité des paramètres
        if (item == null) {
            throw new ValidationException("Item object is null");
        }
        if (product == null) {
            throw new ValidationException("Item must be attached to a product");
        }

        item.setProduct(product);

        // On modifie l'objet de la base de données
        em.merge(item);

        logger.exiting(cname, mname, item);
        return item;
    }

    @Override
    public List<Item> findItems(int firstItem, int batchSize) {
        final String mname = "findCategories";
        logger.entering(cname, mname);

        Query query;
        List<Item> items;

        // On modifie l'objet de la base de données
        query = em.createQuery("SELECT i FROM Item i ORDER BY i.name");
        query.setMaxResults(batchSize);
        query.setFirstResult(firstItem);
        items = query.getResultList();

        logger.exiting(cname, mname, items.size());
        return items;
    }

    @Override
    public List<Item> searchItems(final String keyword, int start, int chunkSize) {
        final String mname = "searchItems";
        logger.entering(cname, mname, keyword);

        Query query;
        List<Item> items;

        // On modifie l'objet de la base de données

3A/sibd/pgmshop/src/main/webapp/about.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

    <ui:composition template="template/default.xhtml">

        <ui:define name="title">À propos de nous</ui:define>
        <ui:define name="content">
            <h:messages layout="table" styleClass="error"/>


            <div class="item">
                <div class="head">À propos de nous</div>
                <div class="content">
                    <p>Nous sommes une bande joyeux compères qui aimons coder du
                    Java parce qu'on trouve que c'est un langage qui est trop
                    bien.</p>

                    <p>En outre, nous aimons les girafes et les gaufres, si vous
                    avez un moyen quelconque de nous donner à titre gracieux l'une de
                    ces deux choses nous vous en seront reconnaissants :-).</p>

		    <p>Cette application a été codée par :</p>
		    <ul>
			    <li>Ionuţ Iortoman</li>
			    <li>Rémy Léone</li>
			    <li>Marc van der Wal</li>
		    </ul>
                </div>
            </div>

            <div class="item">
                <div class="head">À propos de cette application</div>
                <div class="content">
		    Cette application pgmshop a pour but de permettre aux
		    gamerz d'acheter tout leur matos. En outre,
		    ça nous permet d'acheter des tickets pour 
                    aller au zoo et d'aller aussi à Darty pour acheter un 
                    gaufrier.
                </div>
            </div>
        </ui:define>
    </ui:composition>
</html>

3A/sibd/pgmshop/src/main/webapp/createaccount.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

    <ui:composition template="template/default.xhtml">
        <ui:param name="title" value="pgmshop | Création de compte" />
        <ui:define name="content">
            <ui:define name="pagecontenttitle">Création de compte</ui:define>

            <h:messages layout="table" styleClass="error"/>

            <h:form>

                <div class="zoneEditor">
                    <h3>Informations personnelles</h3>

                    <h:panelGrid columns="2">
                        <h:outputText value="Login :"/>
                        <h:inputText value="#{account.user.userName}" readonly="true"/>

                        <h:outputText value="*Prénom :"/>
                        <h:inputText value="#{account.customer.firstname}"/>

                        <h:outputText value="*Nom :"/>
                        <h:inputText value="#{account.customer.lastname}"/>

                        <h:outputText value="Adresse e-mail :"/>
                        <h:inputText value="#{account.customer.email}"/>

                        <h:outputText value="Téléphone :"/>
                        <h:inputText value="#{account.customer.telephone}"/>

                    </h:panelGrid>
                </div>

                <div class="zoneEditor">
                    <h3>Addresse</h3>

                    <h:panelGrid columns="2">
                        <h:outputText value="*Adresse :"/>
                        <h:inputText value="#{account.homeAddress.street}"/>

                        <h:outputText value="*Code postal :"/>
                        <h:inputText value="#{account.homeAddress.zipcode}"/>

                        <h:outputText value="*Ville :"/>
                        <h:inputText value="#{account.homeAddress.city}"/>

                        <h:outputText value="Région/État :"/>
                        <h:inputText value="#{account.homeAddress.state}"/>

                        <h:outputText value="*Pays :"/>
                        <h:inputText value="#{account.homeAddress.country}"/>

                    </h:panelGrid>
                </div>

                <div class="zoneButton">
                    <h:commandButton value="Submit" action="#{account.doCreateUser}" type="submit"/>
                </div>
            </h:form>
        </ui:define>
    </ui:composition>
</html>

3A/sibd/pgmshop/src/main/webapp/orderconfirmed.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html">


    <ui:composition template="template/default.xhtml">
        <ui:define name="titre">Commande confirmée !</ui:define>
        <ui:define name="content">
            <h:messages layout="table" styleClass="error" showDetail="true"/>

            <div class="item">
                <div class="head">
                    <h:outputText value="Votre commande est confirmée : " />
                    <h:outputText value="#{cart.order.id}"/>
                </div>

                <div class="content">
                    <p><b>Votre numéro de commande est : <h:outputText value="#{cart.order.id}"/></b></p>

                    <h:form>
                        <h:dataTable value="#{cart.order.orderLines}" var="orderLine">
                            <h:column>
                                <b><h:outputText value="#{orderLine.item.product.name}"/></b>
                                <br/>
                                <h:outputText value="#{orderLine.item.name}"/>
                            </h:column>
                            <h:column>
                                <h:outputText value="#{orderLine.quantity}"/>
                            </h:column>
                            <h:column>
                                x
                                <h:outputText value="#{orderLine.item.unitCost}">
                                    <f:convertNumber pattern="# ### ##0.00 €" />
                                </h:outputText>
                            </h:column>
                            <h:column>
                                = <h:outputText value="#{orderLine.subTotal}">
                                    <f:convertNumber pattern="# ### ##0.00 €" />
                                </h:outputText>
                            </h:column>
                        </h:dataTable>
                        <br/>

                        <div class="zoneButton">
                            Total :
                            <h:outputText value="#{cart.order.total}">
                                <f:convertNumber pattern="# ### ##0.00 €" />
                            </h:outputText>
                        </div>
                    </h:form>

                    <p>Merci d'avoir fait vos achats chez PGM Shop !</p>
                </div>
            </div>
        </ui:define>
    </ui:composition>
</html>

3A/sibd/pgmshop/src/main/webapp/showcart.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:c="http://java.sun.com/jsp/jstl/core"
      xmlns:ui="http://java.sun.com/jsf/facelets">

    <ui:composition template="template/default.xhtml">
        <ui:define name="title">pgmshop - Panier</ui:define>
        <ui:define name="content">
            <div class="item">
                <div class="head">Mon panier</div>
                <div class="content">

                    <h:messages layout="table" styleClass="error" />

                    <c:choose>
                        <!-- Panier vide -->

                        <c:when test="${empty sessionScope.cart.cartItems}">
                            <p><b>Le panier est vide.</b></p>
                        </c:when>

                        <!-- Panier non vide -->
                        <c:otherwise>
                            <h:form>
                                <h:dataTable value="#{cart.cartItems}" var="cartItem">
                                    <h:column>
                                        <h:commandLink action="#{catalog.doFindItem}">
                                            <h:outputText value="#{cartItem.item.name}"/>
                                            <f:param name="itemId" value="#{cartItem.item.id}"/>
                                        </h:commandLink>
                                    </h:column>
                                    <h:column>
                                        <h:inputText value="#{cartItem.quantity}"/>
                                    </h:column>
                                    <h:column>
                                        ×
                                        <h:outputText value="#{cartItem.item.unitCost}">
                                            <f:convertNumber pattern="# ### ##0.00 €" />
                                        </h:outputText>
                                    </h:column>
                                    <h:column>
                                        = <h:outputText value="#{cartItem.subTotal}">
                                            <f:convertNumber pattern="# ### ##0.00 €" />
                                        </h:outputText>
                                    </h:column>
                                    <h:column>     
                                        <h:commandLink action="#{cart.removeItemFromCart}">
                                            <h:outputText value="Supprimer"/>
                                            <f:param name="itemId" value="#{cartItem.item.id}"/>
                                        </h:commandLink>
                                    </h:column>
                                    <h:column>
                                        <h:commandLink action="#{cart.updateQuantity}">
                                            <h:outputText value="Rafraîchir"/>
                                            <f:param name="itemId" value="#{cartItem.item.id}"/>
                                        </h:commandLink>
                                    </h:column>
                                </h:dataTable>

                                <br/>

                                <div class="zoneButton">
                                    Total :  
                                    <h:outputText value="#{cart.total}"/>

                                    &nbsp;€<br />
                                    <h:commandLink action="#{cart.checkout}">
                                        <h:outputText value="Passer la commande"/>
                                    </h:commandLink>
                                </div>
                            </h:form>
                        </c:otherwise>
                    </c:choose>
                </div>
            </div>
        </ui:define>
    </ui:composition>
</html>

3A/sibd/pgmshop/src/main/webapp/showitems.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"      
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:c="http://java.sun.com/jstl/core">

    <f:view>
        <ui:composition template="template/default.xhtml">
            <ui:define name="title">pgmshop - Items</ui:define>
            <ui:define name="content">
                <h:messages layout="table" styleClass="error"/>

                <div class="item">
                    <div class="head">
                        <h:outputFormat value="Produit : {0}">
                            <f:param value="#{catalog.product.name}" />
                        </h:outputFormat>
                    </div>

                    <div class="content">
                        <h:form>
                            <h:outputText value="Item #{item.firstItem + 1}..#{item.lastItem} of #{item.itemCount}"/>
                            <h:commandLink action="#{item.prev}"
                                           value="Previous #{item.batchSize}" 
                                           rendered="#{item.firstItem >=item.batchSize}"/> 
                            <h:dataTable value="#{catalog.items}" 
                                         var="item" 
                                         columnClasses="first,price,add2cart">
                                <h:column>
                                    <f:facet name="header">
                                        <h:outputText value="Article" />
                                    </f:facet>
                                    <h:commandLink action="#{catalog.doFindItem}">
                                        <h:outputText value="#{item.name}"/>
                                        <f:param name="itemId" value="#{item.id}"/>
                                    </h:commandLink>
                                </h:column>

                                <h:column>
                                    <f:facet name='header'>
                                        <h:outputText value="Prix" />
                                    </f:facet>
                                    <h:outputText value="#{item.unitCost}">
                                        <f:convertNumber pattern="# ### ##0.00 €" />
                                    </h:outputText>
                                </h:column>

                                <c:if test="${not empty sessionScope.account}">
                                    <h:column>
                                        <c:if test="${item.qty ge 0}">
                                            <h:commandLink action="#{cart.addItemToCart}">
                                                <h:outputText value="Ajouter au panier"/>
                                                <f:param name="itemId" value="#{item.id}"/>
                                            </h:commandLink>
                                        </c:if>
                                    </h:column>
                                </c:if>
                            </h:dataTable>
                        </h:form>
                    </div>
                </div>
            </ui:define>
        </ui:composition>
    </f:view>
</html>